# Generated by Django 3.1 on 2021-01-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flikcr_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteplaces',
            name='locationName',
        ),
        migrations.AddField(
            model_name='favouriteplaces',
            name='url',
            field=models.URLField(default='0000000'),
        ),
    ]
