# Generated by Django 3.1 on 2021-01-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flikcr_api', '0002_auto_20210124_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteplaces',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
